version: "3.9"
services:
  postgres:
    image: postgres:latest
    user: postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - my-network
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/postgres -user=postgres -password=postgres -locations=filesystem:/flyway/sql -connectRetries=10  migrate
    volumes:
      - ${PWD}/migrations/sql:/flyway/sql
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - my-network
  app:
    container_name: user
    build: .
    image: vojnic/user:userMS
    depends_on:
      postgres:
          condition: service_healthy
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    networks:
      - my-network
  appcmd:
    container_name: cmd
    image: vojnic/cmd:cmdMS
    ports:
      - "40000:40000"
    environment:
      - PORT=8000
    networks:
      - my-network
networks:
  my-network:
    driver: bridge